#!/usr/bin/env python3
"""Convert YOLO-format auto-labeled data to COCO JSON for RF-DETR training.

Input directory must contain images/ and labels/ subdirectories, as produced
by lodestar_autolabeler.py.

Usage:
    # Single annotations.json (split via config.yaml train_experiments later)
    python yolo_to_coco.py --input <dir> --output <dir>

    # Pre-split train/valid/test output (ready to point config.yaml at directly)
    python yolo_to_coco.py --input <dir> --output <dir> --split 0.8 0.1 0.1
"""

import argparse
import json
import random
import shutil
import sys
from collections import defaultdict
from pathlib import Path

from PIL import Image


CATEGORIES = [{"id": 1, "name": "particle", "supercategory": "none"}]


def _parse_args():
    parser = argparse.ArgumentParser(description="Convert YOLO labels to COCO JSON for RF-DETR.")
    parser.add_argument("--input", required=True, help="Directory containing images/ and labels/")
    parser.add_argument("--output", required=True, help="Destination directory")
    parser.add_argument(
        "--split",
        nargs=3,
        type=float,
        metavar=("TRAIN", "VAL", "TEST"),
        help="Train/val/test fractions summing to 1.0 (e.g. 0.8 0.1 0.1). "
        "Omit to produce a single annotations.json.",
    )
    parser.add_argument(
        "--copy",
        action="store_true",
        help="Copy images instead of symlinking (default: symlink)",
    )
    parser.add_argument(
        "--seed", type=int, default=42, help="Random seed for split shuffle (default: 42)"
    )
    return parser.parse_args()


def _read_image_size(img_path: Path):
    with Image.open(img_path) as img:
        return img.size  # (width, height)


def _yolo_line_to_coco(line: str, img_width: int, img_height: int, image_id: int, ann_id: int):
    parts = line.strip().split()
    if len(parts) < 5:
        return None
    cx_n, cy_n, w_n, h_n = map(float, parts[1:5])
    abs_w = round(w_n * img_width, 2)
    abs_h = round(h_n * img_height, 2)
    abs_x = round(cx_n * img_width - abs_w / 2, 2)
    abs_y = round(cy_n * img_height - abs_h / 2, 2)
    return {
        "id": ann_id,
        "image_id": image_id,
        "category_id": 1,
        "bbox": [abs_x, abs_y, abs_w, abs_h],
        "area": round(abs_w * abs_h, 2),
        "iscrowd": 0,
    }


def _build_coco(entries):
    """Build a COCO dict from a list of (image_record, [annotation_records])."""
    images, annotations = [], []
    for img_rec, ann_recs in entries:
        images.append(img_rec)
        annotations.extend(ann_recs)
    return {
        "info": {"description": "Generated by yolo_to_coco.py", "version": "1.0"},
        "licenses": [],
        "categories": CATEGORIES,
        "images": images,
        "annotations": annotations,
    }


def _place_image(src: Path, dest_dir: Path, copy: bool, dest_name: str | None = None):
    dst = dest_dir / (dest_name or src.name)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    if copy:
        shutil.copy2(src, dst)
    else:
        dst.symlink_to(src.resolve())


def _discover_datasets(input_dir: Path) -> list[tuple[Path, Path, str]]:
    """Return (images_dir, labels_dir, stem_prefix) for each dataset found.

    Handles two layouts produced by lodestar_autolabeler.py:
      - Flat:  <input>/images/  + <input>/labels/          (--output-dir run)
      - Nested: <input>/<stem>_dataset/images/ + .../labels/  (default run)
    """
    if (input_dir / "images").is_dir() and (input_dir / "labels").is_dir():
        return [(input_dir / "images", input_dir / "labels", "")]

    datasets = []
    for subdir in sorted(input_dir.iterdir()):
        if subdir.is_dir() and (subdir / "images").is_dir() and (subdir / "labels").is_dir():
            prefix = subdir.name.removesuffix("_dataset")
            datasets.append((subdir / "images", subdir / "labels", prefix))
    return datasets


def _video_stem(filename: str) -> str:
    """Extract the TIF stem from an autolabeler filename.

    lodestar_autolabeler.py names frames as '<tif_stem>_frame_NNNNN.png' when
    --output-dir is used, or 'frame_NNNNN.png' for a single-TIF run.
    """
    name = Path(filename).stem  # drop extension
    if "_frame_" in name:
        return name.rsplit("_frame_", 1)[0]
    return name  # single-video run: each frame is its own "stem"; treated as one group


def main():
    args = _parse_args()
    input_dir = Path(args.input)
    output_dir = Path(args.output)

    datasets = _discover_datasets(input_dir)
    if not datasets:
        sys.exit(
            f"Error: no dataset found in {input_dir}. "
            "Expected images/ and labels/ subdirectories, or nested <stem>_dataset/ folders."
        )

    if args.split:
        total = sum(args.split)
        if abs(total - 1.0) > 1e-6:
            sys.exit(f"Error: --split fractions must sum to 1.0 (got {total:.4f})")

    if len(datasets) > 1:
        print(f"Found {len(datasets)} dataset(s) under {input_dir}:")
        for images_dir, _, prefix in datasets:
            print(f"  {prefix}/")

    valid_exts = {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp"}

    # Build per-image records across all discovered datasets
    # src_map: coco file_name → original source path (for _place_image)
    entries = []  # list of (image_record, [annotation_records])
    src_map: dict[str, Path] = {}
    image_id = 1
    ann_id = 1
    skipped = 0

    for images_dir, labels_dir, prefix in datasets:
        img_paths = sorted(
            [p for p in images_dir.iterdir() if p.suffix.lower() in valid_exts],
            key=lambda p: p.name,
        )
        for img_path in img_paths:
            lbl_path = labels_dir / (img_path.stem + ".txt")
            if not lbl_path.exists():
                skipped += 1
                continue

            try:
                img_width, img_height = _read_image_size(img_path)
            except Exception as e:
                print(f"  Warning: could not read {img_path.name}: {e} — skipping")
                skipped += 1
                continue

            # Prefix filename with dataset stem to avoid collisions across sub-datasets
            fname = f"{prefix}_{img_path.name}" if prefix else img_path.name
            src_map[fname] = img_path

            img_rec = {"id": image_id, "file_name": fname, "width": img_width, "height": img_height}

            ann_recs = []
            with open(lbl_path) as f:
                for line in f:
                    ann = _yolo_line_to_coco(line, img_width, img_height, image_id, ann_id)
                    if ann:
                        ann_recs.append(ann)
                        ann_id += 1

            entries.append((img_rec, ann_recs))
            image_id += 1

    if not entries:
        sys.exit("Error: no labeled images found — nothing to convert.")

    if skipped:
        print(f"Warning: skipped {skipped} images with no matching label file.")

    # Write output
    output_dir.mkdir(parents=True, exist_ok=True)

    if not args.split:
        # Format A: single annotations.json — split later via config.yaml train_experiments
        img_out = output_dir / "images"
        img_out.mkdir(exist_ok=True)
        for img_rec, _ in entries:
            _place_image(src_map[img_rec["file_name"]], img_out, args.copy, img_rec["file_name"])
        coco = _build_coco(entries)
        ann_path = output_dir / "annotations.json"
        with open(ann_path, "w") as f:
            json.dump(coco, f, indent=2)

        # Show detected video stems so user can paste them into config.yaml
        stems = sorted({_video_stem(img_rec["file_name"]) for img_rec, _ in entries})
        print(f"Converted {len(entries)} images, {ann_id - 1} annotations → {ann_path}")
        print(
            f"\nDetected {len(stems)} video(s) — assign to train_experiments / val_experiments / test_experiments in config.yaml:"
        )
        for s in stems:
            print(f"  - {s}")
    else:
        # Format B: pre-split train/valid/test — splits at the VIDEO level to avoid
        # data leakage between near-identical consecutive frames from the same TIF.
        video_groups: dict[str, list] = defaultdict(list)
        for entry in entries:
            video_groups[_video_stem(entry[0]["file_name"])].append(entry)

        videos = sorted(video_groups)
        rng = random.Random(args.seed)
        rng.shuffle(videos)

        n = len(videos)
        if n < 2:
            sys.exit(
                f"Error: --split requires at least 2 distinct videos; found {n}. "
                "Use the no-split mode and configure train_experiments in config.yaml instead."
            )

        n_train = max(1, round(args.split[0] * n))
        n_val = max(0, round(args.split[1] * n))
        # test gets whatever remains so counts always add up
        split_videos = {
            "train": videos[:n_train],
            "valid": videos[n_train : n_train + n_val],
            "test": videos[n_train + n_val :],
        }

        for split_name, svids in split_videos.items():
            split_entries = [e for v in svids for e in video_groups[v]]
            split_dir = output_dir / split_name
            split_dir.mkdir(exist_ok=True)
            for img_rec, _ in split_entries:
                _place_image(
                    src_map[img_rec["file_name"]], split_dir, args.copy, img_rec["file_name"]
                )
            coco = _build_coco(split_entries)
            ann_path = split_dir / "_annotations.coco.json"
            with open(ann_path, "w") as f:
                json.dump(coco, f, indent=2)
            vids_str = ", ".join(svids) if svids else "(none)"
            print(
                f"  {split_name:5s}: {len(split_entries):4d} images, "
                f"{len(coco['annotations']):5d} annotations  "
                f"[videos: {vids_str}]"
            )
        print(f"\nConverted {len(entries)} images across {n} videos → {output_dir}")


if __name__ == "__main__":
    main()
